name: flutter_google_map
description: A new Flutter application to demonstrate google map integration.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^5.1.5
  permission_handler: ^3.0.1
  google_maps_flutter: ^0.5.19
  fluttertoast: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-Regular.otf
    - family: DINOT
      fonts:
        - asset: fonts/DINOT-Regular.ttf
        - asset: fonts/DINOT-Bold.otf
          weight: 700
    - family: Cookie
      fonts:
        - asset: fonts/Cookie-Regular.ttf
  assets:
    - assets/map_style.json
